### ISSUE TITLE
Gologin spawn error

### ISSUE THREAD

**Issue by new-sameer** [gologinapp/pygologin#18]
Why I am Not able to launch orbita

PS C:\Users\aarif002\Desktop\pygologin-main\main-pygo> py gologin-selenium.py
executablePath C:\Users\aarif002\.gologin/browser/orbita-browser/chrome
Traceback (most recent call last):
  File "C:\Users\aarif002\Desktop\pygologin-main\main-pygo\gologin-selenium.py", line 21, in <module>
    debugger_address = gl.start()
  File "C:\Users\aarif002\Desktop\pygologin-main\main-pygo\gologin.py", line 125, in start
    return self.spawnBrowser()
  File "C:\Users\aarif002\Desktop\pygologin-main\main-pygo\gologin.py", line 109, in spawnBrowser
    subprocess.Popen(params, start_new_session=True)
  File "C:\Users\aarif002\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\aarif002\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by denbelii506** [comment]
me too
