### ISSUE TITLE
An error occurred, selenium cannot call the profile with the agent, but it can be started manually

### ISSUE THREAD

**Issue by kiookp** [gologinapp/pygologin#42]
Traceback (most recent call last):
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/socks.py", line 809, in connect
    negotiate(self, dest_addr, dest_port)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/socks.py", line 443, in _negotiate_SOCKS5
    self.proxy_peername, self.proxy_sockname = self._SOCKS5_request(
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/socks.py", line 524, in _SOCKS5_request
    resp = self._readall(reader, 3)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/socks.py", line 278, in _readall
    raise GeneralProxyError("Connection closed unexpectedly")
socks.GeneralProxyError: Connection closed unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/contrib/socks.py", line 115, in _new_conn
    conn = socks.create_connection(
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/socks.py", line 209, in create_connection
    raise err
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/socks.py", line 814, in connect
    raise GeneralProxyError("Socket error", error)
socks.GeneralProxyError: Socket error: Connection closed unexpectedly

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/connection.py", line 604, in connect
    self.sock = sock = self._new_conn()
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/contrib/socks.py", line 146, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1047f5e20>: Failed to establish a new connection: Connection closed unexpectedly

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='time.gologin.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1047f5e20>: Failed to establish a new connection: Connection closed unexpectedly'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eypi/PycharmProjects/gologin/pygologin/单线程测试.py", line 110, in <module>
    debugger_address = gl.start()
  File "/Users/eypi/PycharmProjects/gologin/pygologin/gologin.py", line 148, in start
    profile_path = self.createStartup()
  File "/Users/eypi/PycharmProjects/gologin/pygologin/gologin.py", line 470, in createStartup
    self.updatePreferences()
  File "/Users/eypi/PycharmProjects/gologin/pygologin/gologin.py", line 454, in updatePreferences
    gologin = self.convertPreferences(profile)
  File "/Users/eypi/PycharmProjects/gologin/pygologin/gologin.py", line 340, in convertPreferences
    self.tz = self.getTimeZone()
  File "/Users/eypi/PycharmProjects/gologin/pygologin/gologin.py", line 251, in getTimeZone
    data = requests.get('https://time.gologin.com', proxies=proxies)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/eypi/anaconda3/envs/gologin/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='time.gologin.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x1047f5e20>: Failed to establish a new connection: Connection closed unexpectedly'))

**Comment by nikita5526** [comment]
@kiookp 
Hello!
I correctly understood that in headless mode you do not start a profile with a proxy type SOCKS but at the same time from the application (GoLogin App) the same profile starts correctly?
